# Clase 10
        


## Ejercicio 1.0
inportar numpy como np y otros recursos como math

In [43]:
import numpy as np
import math

## Ejercicio 1.1

repaso creacion de array

In [23]:
array10 = np.array([1,2,3,4,5,6])
array11 = np.array([7,8,8,4,5,6])
array10


array([1, 2, 3, 4, 5, 6])

In [24]:
print(array10 - array11)

[-6 -6 -5  0  0  0]


## Ejercicio 1.2

matrices

In [25]:
matriz1 = np.array([[1,2],[3,4]]) #matriz de 2 columnas por 2 filas
print(matriz1)

[[1 2]
 [3 4]]


In [26]:
# matriz de 2 columnas y 4 filas
matriz2 = np.array([[1,2],[3,4],[5,6],[7,8]])
print(matriz2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [27]:
# matriz de 3 columnnas por 3 filas
matriz3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
#matriz de 4 columnas y 3 filas
matriz4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matriz4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
matriz4.ndim

2

## Ejercicio 1.3

ecuaciones lineales con numpy

2x + 3y = 5
4x - 1y = 2

In [30]:
coef = np.array([[2,3],[4,-1]])
const = np.array([5,2])

solucion = np.linalg.solve(coef, const)
print(solucion)

[0.78571429 1.14285714]


## Ejercicio 1.4

operaciones con matrices

In [31]:
matrizW = np.array([[[1,2,3,5]],[[8,9,5,8]],[[4,6,5,8]]])
print(matrizW)

[[[1 2 3 5]]

 [[8 9 5 8]]

 [[4 6 5 8]]]


In [32]:
# podemos ver la cantidad de dimenciones de un array
matrizW.ndim

3

In [33]:
matrizW.size

12

In [34]:
matrizW.shape

(3, 1, 4)

In [35]:
matrizA = np.array([[1,2],[3,4]])
matrizB = np.array([[5,6],[7,8]])

print(matrizA)
print("-------")
print(matrizB)



[[1 2]
 [3 4]]
-------
[[5 6]
 [7 8]]


In [36]:
print("Producto matricial")
matriz_producto = np.matmul(matrizA,matrizB)
print(matriz_producto)

Producto matricial
[[19 22]
 [43 50]]


In [37]:
print("Matriz transpuesta")
matriz_transpuesta_A = np.transpose(matrizA)
print(matriz_transpuesta_A)

Matriz transpuesta
[[1 3]
 [2 4]]


In [38]:
print("matriz c original")
matrizC = np.array([[0,1,2,3],[4,5,6,7]])
print(matrizC)
print("-------")
matriz_transpuesta_C = np.transpose(matrizC)
print("Matriz transpuesta")
print(matriz_transpuesta_C)

matriz c original
[[0 1 2 3]
 [4 5 6 7]]
-------
Matriz transpuesta
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [45]:
print("matriz a original") #solo matrices cuadradas poseen determinante
print(matrizA)
print("-------")
determinanteA = np.linalg.det(matrizA)
print("Determinante de la matriz")
print(determinanteA)

matriz a original
[[1 2]
 [3 4]]
-------
Determinante de la matriz
-2.0000000000000004


### Ejercicio 1.8

array con numeros aleatorios

In [ ]:
# creamos un objeto del generador de numreos aleatorios
rng = np.random.default_rng()

In [ ]:
rng.random(4)

In [ ]:
rng.integers(5, size=(2,4))