## Clase 10


## Ejercicio 1.0
inportar numpy como np

In [1]:
import numpy as np

## Ejercicio 1.1

In [2]:
array10 = np.array([1,2,3,4,5,6])
array11 = np.array([7,8,8,4,5,6])
array10


array([1, 2, 3, 4, 5, 6])

In [3]:
print(array10 - array11)

[-6 -6 -5  0  0  0]


## Ejercicio 1.3

ecuaciones lineales con numpy

2x + 3y = 5
4x - 1y = 2

In [4]:
coef = np.array([[2,3],[4,-1]])
const = np.array([5,2])

solucion = np.linalg.solve(coef, const)
print(solucion)

[0.78571429 1.14285714]


### Ejercicio 1.4

In [5]:
matrizW = np.array([[[1,2,3,5]],[[8,9,5,8]],[[4,6,5,8]]])
print(matrizW)

[[[1 2 3 5]]

 [[8 9 5 8]]

 [[4 6 5 8]]]


In [6]:
# podemos ver la cantidad de dimenciones de un array
matrizW.ndim

3

In [7]:
matrizW.size

12

In [8]:
matrizW.shape

(3, 1, 4)

### Ejercicio 1.8

array con numeros aleatorios

In [15]:
# creamos un objeto del generador de numreos aleatorios
rng = np.random.rand