# Clase 10
        


## Ejercicio 1.0
inportar numpy como np

In [1]:
import numpy as np

## Ejercicio 1.1

repaso creacion de array

In [2]:
array10 = np.array([1,2,3,4,5,6])
array11 = np.array([7,8,8,4,5,6])
array10


array([1, 2, 3, 4, 5, 6])

In [3]:
print(array10 - array11)

[-6 -6 -5  0  0  0]


## Ejercicio 1.2

matrices

In [12]:
matriz1 = np.array([[1,2],[3,4]]) #matriz de 2 columnas por 2 filas
print(matriz1)

[[1 2]
 [3 4]]


In [11]:
# matriz de 2 columnas y 4 filas
matriz2 = np.array([[1,2],[3,4],[5,6],[7,8]])
print(matriz2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
# matriz de 3 columnnas por 3 filas
matriz3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#matriz de 4 columnas y 3 filas
matriz4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matriz4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
matriz4.ndim

2

## Ejercicio 1.3

ecuaciones lineales con numpy

2x + 3y = 5
4x - 1y = 2

In [5]:
coef = np.array([[2,3],[4,-1]])
const = np.array([5,2])

solucion = np.linalg.solve(coef, const)
print(solucion)

[0.78571429 1.14285714]


## Ejercicio 1.4

operaciones con matrices

In [6]:
matrizW = np.array([[[1,2,3,5]],[[8,9,5,8]],[[4,6,5,8]]])
print(matrizW)

[[[1 2 3 5]]

 [[8 9 5 8]]

 [[4 6 5 8]]]


In [7]:
# podemos ver la cantidad de dimenciones de un array
matrizW.ndim

3

In [8]:
matrizW.size

12

In [9]:
matrizW.shape

(3, 1, 4)

### Ejercicio 1.8

array con numeros aleatorios

In [16]:
# creamos un objeto del generador de numreos aleatorios
rng = np.random.default_rng()

In [18]:
rng.random(4)

array([0.49500628, 0.84997222, 0.7021077 , 0.63215789])

In [19]:
rng.integers(5, size=(2,4))

array([[3, 2, 0, 4],
       [0, 3, 2, 3]])