# Clase 10
        


## Ejercicio 1.0
importar numpy como np y otros recursos como math

In [1]:
import numpy as np
import math

## Ejercicio 1.1

repaso creacion de array

In [2]:
array10 = np.array([1,2,3,4,5,6])
array11 = np.array([7,8,8,4,5,6])
array10


array([1, 2, 3, 4, 5, 6])

In [3]:
print(array10 - array11)

[-6 -6 -5  0  0  0]


## Ejercicio 1.2

matrices

In [4]:
matriz1 = np.array([[1,2],[3,4]]) #matriz de 2 columnas por 2 filas
print(matriz1)

[[1 2]
 [3 4]]


In [5]:
# matriz de 2 columnas y 4 filas
matriz2 = np.array([[1,2],[3,4],[5,6],[7,8]])
print(matriz2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
# matriz de 3 columnnas por 3 filas
matriz3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#matriz de 4 columnas y 3 filas
matriz4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matriz4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
matriz4.ndim

2

## Ejercicio 1.3

ecuaciones lineales con numpy

2x + 3y = 5
4x - 1y = 2

In [9]:
coef = np.array([[2,3],[4,-1]])
const = np.array([5,2])

solucion = np.linalg.solve(coef, const)
print(solucion)

[0.78571429 1.14285714]


## Ejercicio 1.4

operaciones con matrices

In [10]:
matrizW = np.array([[[1,2,3,5]],[[8,9,5,8]],[[4,6,5,8]]])
print(matrizW)

[[[1 2 3 5]]

 [[8 9 5 8]]

 [[4 6 5 8]]]


In [11]:
# podemos ver la cantidad de dimenciones de un array
matrizW.ndim

3

In [12]:
matrizW.size

12

In [13]:
matrizW.shape

(3, 1, 4)

In [14]:
matrizA = np.array([[1,2],[3,4]])
matrizB = np.array([[5,6],[7,8]])

print(matrizA)
print("-------")
print(matrizB)



[[1 2]
 [3 4]]
-------
[[5 6]
 [7 8]]


In [15]:
print("Producto matricial")
matriz_producto = np.matmul(matrizA,matrizB)
print(matriz_producto)

Producto matricial
[[19 22]
 [43 50]]


In [16]:
print("Matriz transpuesta")
matriz_transpuesta_A = np.transpose(matrizA)
print(matriz_transpuesta_A)

Matriz transpuesta
[[1 3]
 [2 4]]


In [17]:
print("matriz c original")
matrizC = np.array([[0,1,2,3],[4,5,6,7]])
print(matrizC)
print("-------")
matriz_transpuesta_C = np.transpose(matrizC)
print("Matriz transpuesta")
print(matriz_transpuesta_C)

matriz c original
[[0 1 2 3]
 [4 5 6 7]]
-------
Matriz transpuesta
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [18]:
print("matriz a original") #solo matrices cuadradas poseen determinante
print(matrizA)
print("-------")
determinanteA = np.linalg.det(matrizA)
print("Determinante de la matriz")
print(determinanteA)

matriz a original
[[1 2]
 [3 4]]
-------
Determinante de la matriz
-2.0000000000000004


### Ejercicio 1.8

array con numeros aleatorios

In [19]:
# creamos un objeto del generador de numreos aleatorios
rng = np.random.default_rng()

In [20]:
rng.random(4)

array([0.2221894 , 0.25377321, 0.75716008, 0.87134169])

In [21]:
rng.integers(5, size=(2,4))

array([[2, 0, 2, 1],
       [3, 3, 0, 4]])

## Ejercicio 1.9

Contar valores unicos dentro de un array

In [22]:
array_repetido = np.array([11,11,12,12,12,13,14,15,15,16,17,20,19,19])

array_unico = np.unique(array_repetido)
array_unico

array([11, 12, 13, 14, 15, 16, 17, 19, 20])

# Parte A

Tenemos una funcion cubica con la forma(3x^3-7x^2+6*x+9)

In [23]:
def mi_calculo(x):
    return 3 * x**3 - 7 * x**2 + 6 * x + 9

## Ejercicio 2.1

Calcular cuales serian los valores obtenidos al pasarle como argumentos los valores pares desde 0 a 20 incluyendo ambos. Guardar el resultado en un array.

In [24]:
lista_valores = []
for i in range(0, 21, 2):
    lista_valores.append(i)
input_array = np.array(lista_valores)
input_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
output_array = mi_calculo(input_array)
output_array

array([    9,    17,   113,   441,  1145,  2369,  4257,  6953, 10601,
       15345, 21329])

## Ejercicio 2.2

Al array que obtuvimos en la sección anterior:

* Calcula la media de los números en el array que contiene los valores calculados.
* Calcula la desviación estándar de los números en el array calculado.
* Encuentra el valor máximo y su índice en el array calculado.
* Crea un nuevo array array_cuadrados que contenga el cuadrado de cada número en calculado.
* Crear un array con la suma acumulativa (a1, a1+a2, a1+a2+a3, .....) de los elementos en array_cuadrados.
* Crear un array con la raiz 5ta de cada valor de array_cuadrados (redondear a 2 decimales).
  
Imprimir los resultados obtenidos.

In [29]:
media = np.mean(output_array)

desviacion_estandar = np.std(output_array)

valor_maximo = np.max(output_array)

indice_maximo = np.argmax(output_array)

array_cuadrados = np.square(output_array)

suma_acumulativa_cuadrados = np.cumsum(array_cuadrados)

array_raiz_quinta = np.power(array_cuadrados, 1/5).round(2)

print("Media:", media)
print("Desviacion estandar:", desviacion_estandar)
print("Valor maximo:", valor_maximo)
print("Indice del valor maximo:", indice_maximo)
print("Valores al cuadrado:", array_cuadrados)
print("Array suma acumulativa de valores al cuadrado:", suma_acumulativa_cuadrados)
print("Array resultado raiz quinta:", array_raiz_quinta)


Media: 5689.0
Desviacion estandar: 6877.906658279102
Valor maximo: 21329
Indice del valor maximo: 10
Valores al cuadrado: [       81       289     12769    194481   1311025   5612161  18122049
  48344209 112381201 235469025 454926241]
Array suma acumulativa de valores al cuadrado: [       81       370     13139    207620   1518645   7130806  25252855
  73597064 185978265 421447290 876373531]
Array resultado raiz quinta: [ 2.41  3.11  6.63 11.42 16.73 22.38 28.29 34.42 40.75 47.25 53.9 ]


## Ejercicio 2.3

Con los arrays que obtuvimos en la sección anterior:

* Calcular el producto escalar (o producto punto) entre los array output y el array raiz quinta.
* Crear un vector con los 3 ultimos valores del array input. Crear un segundo vector con los 3 primeros valores del array suma acumulativa de los cuadrados. Calcular el array que daria como resultado hacer el producto vectorial entre ambos.

In [30]:
reusltado_producto_escalar = np.matmul(output_array,array_raiz_quinta).round(2)
reusltado_producto_escalar

2744461.93

In [31]:
vector1 = input_array[-3:]
vector2 = suma_acumulativa_cuadrados[:3]
reusltado_producto_vec