## INSTALAR MÓDULOS
A la hora de trabajar con módulos es posible que no los tengamos instalados ya que muchos son creados por la comunidad o simplemente no estan incluidos con los archivos base de python.

Para ello podemos usar pip:

En la terminal (local): pip install <nombre_modulo>
En colab ejecutar en una celda: !pip install <nombre_modulo>
## MATH
El módulo math en Python se utiliza para realizar operaciones matemáticas más avanzadas que las disponibles en el conjunto de funciones y permite utilizar constantes matemáticas básicas para manejar problemas más complejos que requieren operaciones matemáticas avanzadas..

Incluye funciones para:

Realizar cálculos trigonométricos
Operaciones de álgebra lineal
Funciones exponenciales y logarítmicas

# Ejercicio 1.0
Importar el módulo math

In [1]:
import math


In [2]:
radio = float(input("Ingrese el radio del circulo: "))
area = math.pi * radio ** 2
print("El area del circulo es : ", area)


Ingrese el radio del circulo:  4


El area del circulo es :  50.26548245743669


# Ejercicio 1.2
Calculadora de Hipotenusa

In [3]:
catet1 = float(input("Ingrese longitud del primer cateto: "))
catet2 = float(input("Ingrese longitud del segundo cateto: "))
hipote = math.sqrt(catet1 ** 2 + catet2 ** 2)
print("La longitud de la hipotenusa de este triangulo es: ", hipote)

Ingrese longitud del primer cateto:  4
Ingrese longitud del segundo cateto:  5


La longitud de la hipotenusa de este triangulo es:  6.4031242374328485


## Ejercicio 1.3
Calculadora seno, coseno, tangente

In [4]:
angulo_grad = float(input("Ingrese el angulo en grados: "))
angulo_radian = math.radians(angulo_grad)

seno = math.sin(angulo_radian)
coseno = math.cos(angulo_radian)
tangente = math.tan(angulo_radian)

print("Seno: ", seno)
print("Coseno: ", coseno)
print("Tangente: ", tangente)

Ingrese el angulo en grados:  30


Seno:  0.49999999999999994
Coseno:  0.8660254037844387
Tangente:  0.5773502691896257


## Ejercicio 1.4
Cálculo de Potencias

In [5]:
base = float(input("Ingrese la base:"))
exponent = float(input("Ingrese el exponente:"))
result = math.pow(base, exponent)
print("El resultado de", base, "elevado a la", exponent, "es:", result)

Ingrese la base: 8
Ingrese el exponente: 2


El resultado de 8.0 elevado a la 2.0 es: 64.0


## Ejercicio 1.5
Área de un Triángulo (fórmula de Herón)

In [7]:
lado1 = 6
lado2 = 7
lado3 = 8

s = (lado1 + lado2 + lado3) / 2

area = math.sqrt(s * (s - lado1) * (s - lado2) * (s - lado3))
print("El area del triangulo es:", area)

El area del triangulo es: 20.33316256758894


## Ejercicio 1.6
Suma de una Serie Infinita (π/4 = 1 - 1/3 + 1/5 - 1/7 + 1/9 - ...)

In [20]:
suma = 0 
caracter = 1001

for i in range(caracter):
    suma += (-1) ** i / (2 * i + 1)

pi = 4 * suma
print("El valor aproximado del numero pi es :", pi)

El valor aproximado del numero pi es: 3.1425916543395442


## NUMPY
NumPy es una biblioteca de Python que ayuda a trabajar con matrices y arreglos multidimensionales.

Con NumPy se puede realizar* :

Multiplicación de matrices/arreg* leos
Inversión de matrices/arre* gleos
Cálculo de funciones trigonomé* tricas
Procesamiento d* e datos
Mmanipulación de matrices grandes de manera rápida y e
  ficiente.
En resumen NumPy se usa para trabajar con datos numéricos en Python.

## Ejercicio 2.0
Importar Numpy pero usando el alias np

In [11]:
import numpy as np

## Ejercicio 2.1
Veamos las operaciones basicas con arrays

In [12]:
arrayPar = np.array([1, 3, 5, 7])
arrayImpar = np.array([2, 4, 6, 8])

suma = arrayPar + arrayImpar
resta = arrayPar - arrayImpar
multiplicacion = arrayPar * arrayImpar
divicion = arrayPar / arrayImpar

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicacion:", multiplicacion)
print("Divicion:", divicion)

Suma: [ 3  7 11 15]
Resta: [-1 -1 -1 -1]
Multiplicacion: [ 2 12 30 56]
Divicion: [0.5        0.75       0.83333333 0.875     ]


## Ejercicio 2.2
Con numpy es muy facil crear matrices, por ejemplo la matriz de Identidad

In [19]:
matriz_identidad = np.eye(12)
print("La matriz de indetidad 12 x 12 luce asi 😁:")
print(matriz_identidad)

La matriz de indetidad 12 x 12 luce asi 😁:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## Ejercicio 2.3
Si trabajamos con vectores podemos calcular el producto escalar de estos

vectorImp = np.array([1, 3, 5])
vectorPar = np.array([2, 4, 6])

product_escalar = np.dot(vectorImp, vectorPar)
print("Producto escalar:", product_escalar)

## Ejercicio 2.4
Otra operación muy común es calcular el vector norma

In [28]:
vector = np.array([3, 6])
norma = np.linalg.norm(vector)
print("Norma del vector:", norma)

Norma del vector: 6.708203932499369


## Ejercicio 2.5
De forma similar es posible realizar operaciones entre matrices usando Numpy

In [30]:
matrizPar = np.array([[2, 4],[6, 8]])
matrizImp = np.array([[1, 3],[5, 7]])

producto_matricial = np.matmul(matrizPar, matrizImp)
transpuesta = np.transpose(matrizPar)
determinante = np.linalg.det(matrizPar)

print("Producto matricial :", producto_matricial)
print("Transpuesta de la matriz:", transpuesta)
print("Determinante de la matriz:", determinante)

Producto matricial : [[22 34]
 [46 74]]
Transpuesta de la matriz: [[2 6]
 [4 8]]
Determinante de la matriz: -8.000000000000002


## Ejercicio 2.6
Numpy tiene una función especifica para resolver ecuaciones lineales

In [33]:
coef = np.array([[2, 4],[5, -2]])
const = np.array([5, 3])

solucion = np.linalg.solve(coef, const)
print("Solucion de sistema de ecuaciones:")
print("x =", solucion[0])
print("y =", solucion[1])

Solucion de sistema de ecuaciones:
x = 0.9166666666666666
y = 0.7916666666666666
