# Clase 12

## Pandas DataFrame

los dataframe son tablas parecidas a una hoja de calculo, contienen filas y columnas. cada una de estas filas individualmente es una Serie

## Ejercicio 1.0

In [62]:
!pip install pandas==2.2.2

In [63]:
import pandas as pd
import numpy as np

## Ejercicio 1.1

creacion objeto DataFrame

In [64]:
# creamos un dataframe extrayendo los datos de las listas
lista_p1 = ["Juan Pablo", "Simone", 56, False]
lista_p2 = ["Yul","Mohurad",46,True]
lista_p3 = ["Cristina","Arreglate",45,False]
lista_p4 = ["Jorge","Rodriguez",38,False]
lista_p5 = ["Sebastian","First",48,False]

lista_nombre_columnas = ["Nombre","Apellido","Edad","Es metido"]

df_alumnos = pd.DataFrame(
    data = [lista_p1,lista_p2,lista_p3,lista_p4,lista_p5],
    columns = lista_nombre_columnas
)
df_alumnos


Nombre   Apellido  Edad  Es metido
0  Juan Pablo     Simone    56      False
1         Yul    Mohurad    46       True
2    Cristina  Arreglate    45      False
3       Jorge  Rodriguez    38      False
4   Sebastian      First    48      False

In [65]:
# podemos crear un dataFrame extrayendo los datos de un diccionario

diccionario_empleados = {
    "Nombre" : ["Mara","Mirta","Jose","Juana"],
    "Departamento" : ["Sales","IT","IT","JR"],
    "Suledo_usd" : [1200,5000,7600,8000],
    "Facturacion" : [True,True,False,True]
}
diccionario_empleados

{'Nombre': ['Mara', 'Mirta', 'Jose', 'Juana'],
 'Departamento': ['Sales', 'IT', 'IT', 'JR'],
 'Suledo_usd': [1200, 5000, 7600, 8000],
 'Facturacion': [True, True, False, True]}

In [66]:
df_empleados = pd.DataFrame(diccionario_empleados)

df_empleados

Nombre Departamento  Suledo_usd  Facturacion
0   Mara        Sales        1200         True
1  Mirta           IT        5000         True
2   Jose           IT        7600        False
3  Juana           JR        8000         True

In [67]:
rng = np.random.default_rng()


In [68]:
array_5x3 = rng.integers(1,20,(5,3)) #creacion array
print(array_5x3)

[[ 5 11  2]
 [ 2  4 16]
 [18  4  8]
 [16 11 13]
 [ 4 15 16]]


In [69]:
array_5x3.ndim

2

In [70]:
array_5x3.shape

(5, 3)

In [71]:
#tambien podemos crear un dataframe a partir de un array


## Ejercicio 1.2

podemos trabajar con indices personalizados

In [72]:
# Estamos integrando el indice a partir de una lista

# dataframe catalogo vehiculos disponibles en una concecionaria

lista_patente = ["GHY-548","ERG-105","TPE-485","POL-896"]

lista_v1 = ["Ford","Mustang",100000,True]
lista_v2 = ["Fiat","500",50000,False]
lista_v3 = ["Toyota","Yaris",75000,True]
lista_v4 = ["Toyota","Corolla",150000,True]

lista_encabezado_concecionaria = ["Marca", "Modelo", "Precio", "0Km"]

df_vehiculos = pd.DataFrame(
    data = [lista_v1,lista_v2,lista_v3,lista_v4],
    columns = lista_encabezado_concecionaria,
    index = lista_patente
)
df_vehiculos


Marca   Modelo  Precio    0Km
GHY-548    Ford  Mustang  100000   True
ERG-105    Fiat      500   50000  False
TPE-485  Toyota    Yaris   75000   True
POL-896  Toyota  Corolla  150000   True

In [73]:
# Podemos seleccionar el indice desde una columna de mi dataframe

#Tengo un diccionario con empleados
diccionario_empleados = {
  "ID":["F-001","C-001","F-002","F-003","F-004","C-002"],
  "Nombre":["Andres","Sofia","Mercedes","Pablo","Claudia","Miguel"],
  "Apellido":["Muñoz","Cerves","Garcia","Alaves","Perez","Solis"],
  "Sueldo":[4500,6000,2300,5300,4920,5000],
  "Departamento":["IT","Sales","IT","IT","HR","Sales"],
  "Facturacion":[True,True,False,True,True,False]
}

df_empleado2 = pd.DataFrame(diccionario_empleados)
df_empleado2

ID    Nombre Apellido  Sueldo Departamento  Facturacion
0  F-001    Andres    Muñoz    4500           IT         True
1  C-001     Sofia   Cerves    6000        Sales         True
2  F-002  Mercedes   Garcia    2300           IT        False
3  F-003     Pablo   Alaves    5300           IT         True
4  F-004   Claudia    Perez    4920           HR         True
5  C-002    Miguel    Solis    5000        Sales        False

In [74]:

df_empleado2.set_index("ID", inplace=True)
df_empleado2

Nombre Apellido  Sueldo Departamento  Facturacion
ID                                                        
F-001    Andres    Muñoz    4500           IT         True
C-001     Sofia   Cerves    6000        Sales         True
F-002  Mercedes   Garcia    2300           IT        False
F-003     Pablo   Alaves    5300           IT         True
F-004   Claudia    Perez    4920           HR         True
C-002    Miguel    Solis    5000        Sales        False

## Ejercicio 1.4

como renombrar columnas e indices en dataframe

In [75]:
dict_concesionaria = {
    'marca': ['Ford','Toyota','Audi','Ford','Ford','Renault','Chevrolet','Ford','Ford','Volkswagen','Honda','BMW','Mercedes-Benz','Ford','Ford'],
    'modelo': ['Focus','Hilux','A3','Mustang','F-100','Cactus','Spark','Escape','Explorer','Gol','Civic','X5','Clase C','Ranger','Fusion'],
    'precio': [3000,10000,10000,20000,2000,3500,4000,18000,25000,6000,8000,15000,12000,22000,17000],
    '0Km': [True,True,True,True,False,True,False,True,False,True,True,True,False,True,False]
  }
dict_concesionaria

{'marca': ['Ford',
  'Toyota',
  'Audi',
  'Ford',
  'Ford',
  'Renault',
  'Chevrolet',
  'Ford',
  'Ford',
  'Volkswagen',
  'Honda',
  'BMW',
  'Mercedes-Benz',
  'Ford',
  'Ford'],
 'modelo': ['Focus',
  'Hilux',
  'A3',
  'Mustang',
  'F-100',
  'Cactus',
  'Spark',
  'Escape',
  'Explorer',
  'Gol',
  'Civic',
  'X5',
  'Clase C',
  'Ranger',
  'Fusion'],
 'precio': [3000,
  10000,
  10000,
  20000,
  2000,
  3500,
  4000,
  18000,
  25000,
  6000,
  8000,
  15000,
  12000,
  22000,
  17000],
 '0Km': [True,
  True,
  True,
  True,
  False,
  True,
  False,
  True,
  False,
  True,
  True,
  True,
  False,
  True,
  False]}

In [76]:
df_conce = pd.DataFrame(dict_concesionaria)
df_conce

marca    modelo  precio    0Km
0            Ford     Focus    3000   True
1          Toyota     Hilux   10000   True
2            Audi        A3   10000   True
3            Ford   Mustang   20000   True
4            Ford     F-100    2000  False
5         Renault    Cactus    3500   True
6       Chevrolet     Spark    4000  False
7            Ford    Escape   18000   True
8            Ford  Explorer   25000  False
9      Volkswagen       Gol    6000   True
10          Honda     Civic    8000   True
11            BMW        X5   15000   True
12  Mercedes-Benz   Clase C   12000  False
13           Ford    Ranger   22000   True
14           Ford    Fusion   17000  False

### Podemos cambiar todos los nombres de las columnas


In [77]:
df_conce.head()

marca   modelo  precio    0Km
0    Ford    Focus    3000   True
1  Toyota    Hilux   10000   True
2    Audi       A3   10000   True
3    Ford  Mustang   20000   True
4    Ford    F-100    2000  False

## Ejercicio 1.5

como agregar o concatenarelementos a un dataframe

In [78]:
df_conce.shape #tenemos 15 filas y 4 columnas

(15, 4)